// <auto-generated />
namespace OAuthIdentity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initdb2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initdb2));
        
        string IMigrationMetadata.Id
        {
            get { return "201707011247266_initdb2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
